### PR TITLE
Blockstates for x=true on vents

### LINKED ISSUE #358: Forged vent visuals don't match up to block's hitbox properly
## Bug Report

**Observed Behaviour**
The forged vents block model does not properly orientate themselves to their hitboxes in north/south directions.

This occurs with forged vents placed in creative and generated in the world.

**Expected Behaviour**
The rendered block to properly face correct direction, in this case it should render the block texture following the block's hitbox like it does when facing east/west.

**Minimal setup needed to reproduce**

- Forge version: 35.1.37
- Tetra version: 1.16.4-3.6.0
- Tetra configuration: Default configuration used.
- Other mods:

**Steps to reproduce**
Try to place forged vent block so it would be facing north/south.

### PR DESCRIPTION
**Pull request by MacyMacerator**
Just a little thing I noticed while putting together a pack with Tetra in it. There might be a more responsible fix, but this is what I have and it works.
Should fix #358

### CODE REVIEW

**Comment by mickelus** [comment]
I don't know how to reproduce this, so I can't test your fix :/

**Comment by MacyMacerator** [comment]
That's very odd, I've had this problem in every version and  instance of tetra that I've run. 

Actually, looking into that, I think I found the more responsible fix. Computer's pretty busy at the moment but I'll test it out when I can.

**Comment by MacyMacerator** [comment]
Okay: Previously mentioned "more responsible" fix works in my test.

It looks like the broken file,
[src/generated/resources/assets/tetra/blockstates/forged_vent.json](https://github.com/mickelus/tetra/blob/master/src/generated/resources/assets/tetra/blockstates/forged_vent.json)
is overriding the functional file,
[src/main/resources/assets/tetra/blockstates/forged_vent.json](https://github.com/mickelus/tetra/blob/master/src/main/resources/assets/tetra/blockstates/forged_vent.json)

Removing version of the file in the \/generated\/ path appears to fix the issue. 


I'm having trouble understanding what you mean by not being able to reproduce the issue.

Do vents in your dev environment properly visually change orientation when their blockstate includes "x=true"? (placed when facing in the +/-x direction)


If that's the case, I'd ask if the first file is present and loading.

**Comment by MacyMacerator** [comment]
The first one was an accident but this should actually stay closed, since there's a more elegant fix than what this pr proposes.

**Pull request closed without merging**
