### PR TITLE
added capability synergies for all pickaxe types

### PR DESCRIPTION
**Pull request by phyne**

### CODE REVIEW

**Comment by mickelus** [comment]
I've been thinking about doing something like this, double pickaxe heads provide an extra tier while pickaxe head + butt would have a faster mining speed (as the butt would reduce the swing speed less).

It's enough to have one entry for that though:
```
{
    "modules": ["duplex/basic_pickaxe", "duplex/basic_pickaxe"],
    "capabilities": {
        "pickaxe": 1
    }
}```

I'm not consistent between files (assets use 2 space indentation while data uses 4) so I shouldn't say much, but you also changed the codestyle completely :P

Fix those two things and I'll merge, or we could close it since I'd have to add the functionality later anyways.

**Comment by phyne** [comment]
Yea the formatting is different because I blew up the condensed json with the notepad++ formatting tool. Also, I didn't use 2 generic pickaxe heads because I wanted specifically 2 of the same material heads to provide the synergy. If this isn't how you intend it to be, then there's no need for a PR.

**Comment by mickelus** [comment]
You're right, two of the same material makes it more interesting.

**Comment by mickelus** [comment]
I fixed the codestyle.

We'd have to update the default tier for the pickaxe heads as well, or you'd be able to mine obsidian with an iron pick.

**Comment by mickelus** [comment]
I've implemented a proper system for this for 1.15, will try to port back to 1.14. Closing!

**Pull request closed without merging**
